//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachIT.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int IdDevice { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime WarrantyEndDate { get; set; }
        public int IdDeviceType { get; set; }
    
        public virtual DeviceTypes DeviceTypes { get; set; }
    }
}
