//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachIT.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationHistory
    {
        public int IdHistory { get; set; }
        public string TableName { get; set; }
        public string OperationType { get; set; }
        public System.DateTime OperationTime { get; set; }
        public Nullable<int> EmployerId { get; set; }
        public string ChangedData { get; set; }
    }
}
