//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachIT.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCDetails
    {
        public int IdPC { get; set; }
        public string CPU { get; set; }
        public int RAM { get; set; }
        public string Storage { get; set; }
        public string GPU { get; set; }
        public Nullable<int> IdDevice { get; set; }
    
        public virtual DeviceTypes DeviceTypes { get; set; }
    }
}
