//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachIT.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintTechonogy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrintTechonogy()
        {
            this.PrinterDetails = new HashSet<PrinterDetails>();
        }
    
        public int IdPrintTechonogy { get; set; }
        public string PrintTechonogyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrinterDetails> PrinterDetails { get; set; }
    }
}
