//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachIT.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int Idrequest { get; set; }
        public int IdStatus { get; set; }
        public string NameRequest { get; set; }
        public int IdCategory { get; set; }
        public int IdPriority { get; set; }
        public System.DateTime PlanDate { get; set; }
        public int IdReq { get; set; }
        public int IdExcutor { get; set; }
        public string Transcription { get; set; }
        public System.DateTime DateRealize { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Employers Employers { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
    }
}
