//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachIT.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Devices = new HashSet<Devices>();
        }
    
        public int IdRequest { get; set; }
        public int IdStatus { get; set; }
        public int IdCategory { get; set; }
        public int IdPriority { get; set; }
        public System.DateTime PlanDate { get; set; }
        public string Transcription { get; set; }
        public Nullable<System.DateTime> DateRealize { get; set; }
        public int IdRequestSender { get; set; }
        public Nullable<int> IdExcutor { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devices> Devices { get; set; }
        public virtual Employers Employers { get; set; }
        public virtual Employers Employers1 { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
    }
}
