//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachIT.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannerDetails
    {
        public int IdScanner { get; set; }
        public string MaxScanResolution { get; set; }
        public double ScanSpeed { get; set; }
        public int IdDocumentFeeder { get; set; }
        public int IdDevice { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual DocumentFeeder DocumentFeeder { get; set; }
    }
}
